### ISSUE TITLE
Practica 1 Mockup en Figma 4BS

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-1-practicaprototipo-topicos_a-4bs-idm#2]
Proyecto de Figma:

https://www.figma.com/file/bmmGPWG00mZTGGjIcOdI6I/Prototipo-de-proyecto?type=design&node-id=0-1&mode=design&t=bHu21HYXjV7bp1bD-0

Integrantes de equipo:
Cruz Cruz Diego
Rosas Garcia Marco Uriel
Jimenez Sanchez Irvin

REPORTE DE PRACTICA:
[Reporte de Practica Mockup.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-practicaprototipo-topicos_a-4bs-idm/files/14196932/Reporte.de.Practica.Mockup.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rúbrica de evacuación del trabajo , consideramos que la calificación es de un 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
